/**
 * Created by 12072 on 06/03/17.
 */
export default {
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_REJECTED: 'FETCH_CATEGORY_REJECTED',
    FETCH_CATEGORY_PENDING: 'FETCH_CATEGORY_PENDING',
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    UPDATE_FILTER: 'UPDATE_FILTER'
};